### ISSUE TITLE
Doesn't show Riftbound Caches

### ISSUE THREAD

**Issue by cremor** [kemayo/wow-minimaprangeextender#1]
Using addon version v4, it seems like the addon doesn't work for Riftbound Caches. Those are the chests that spawn in the Rift phase of Korthia.

I do have all vignette types enabled in the addon's options.

The interesting thing about this issue is that your other addon WhatsOnTheMap does show these chests, even before they are in minimap range. Here is a screenshot that shows the debug information of WhatsOnTheMap while the chest is not yet visible on the minimap (it's the one on the northwest position indicated by HandyNotes):
![WoWScrnShot_080321_211143](https://user-images.githubusercontent.com/116314/128074379-3c0ccc54-2ee0-41ba-aeeb-41a45c175c69.jpg)

**Comment by kemayo** [comment]
Huh, that'd be because they're actually using the `type` field in vignetteInfo as something other than 0 for once. I think there's no particular reason _not_ to expand that now, so I shall investigate that.

**Comment by cremor** [comment]
@kemayo I'm using your update since you pushed that commit and it works fine, thanks!
But could you please release a new version so that others can profit from the change too?
